### ISSUE TITLE
Post Request and Put Request does not support parameter passsing

### ISSUE THREAD

**Issue by momacoy** [bulkan/robotframework-requests#84]
I was trying to issue `POST / PUT` request to `/uri?key=value` with body in `xml` format but it seems that both `POST` and `PUT` request does not support passing of parameters `key=value`.

I have tried the following:
```
${resp}=    Post Request    session1    /uri    params=key=value    data=${body}
```
The following error is encountered:
`TypeError: post_request() got an unexpected keyword argument 'params'`

Is there other way to pass parameters in `POST/PUT` request?

**Comment by oleduc** [comment]
Hi @momacoy, it seems like it is indeed not supported at the moment. However this is a very easy fix, I'll submit a quick PR if you don't want to get involved. 

But if you want to do it yourself this project's author is very active and accepting pull requests.

**Comment by oleduc** [comment]
Done #85

**Comment by momacoy** [comment]
Hi @oleduc,

Thanks! I'm still new in python and robotframework.
Also, regarding:
`${resp}= Post Request session1 /uri?key=value data=${body}`
the following error is encountered:
`TypeError: post_request() got an unexpected keyword argument '/uri?key'`

**Comment by vkosuri** [comment]
@momacoy ```requests >=2.9``` url with params wont work please downgrade it to ```requests 2.8```

**Comment by oleduc** [comment]
@momacoy Actually this is caused by our retry decorator which I removed in my PRs, #86 fixes that issues.

**Comment by momacoy** [comment]
@oleduc Does this means that downgrading to `requests 2.8` would still not work?
Ok, I'll try to fork the project and merge you pull request.
Thanks!

**Comment by oleduc** [comment]
@momacoy I'm positive that it would not.

**Comment by momacoy** [comment]
@oleduc Okay. Thanks!
